boardgame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', include('boardgames.urls')),
]

boardgames/urls.py
"""Defines URL patterns for boardgames"""

from django.urls import path

from . import views

app_name = 'boardgames'
urlpatterns = [
    # Homepage
    path('', views.index, name='index'),
    # Page that shows all the games
    path('games/', views.games, name='games'),
    # Detailed page to show one game and its data
    path('games/<int:game_id>/', views.game, name='game'),
    # Page for adding a new game
    path('new_game/', views.new_game, name='new_game'),
    # Page to show a new loan.
    path('new_loan/<int:game_id>/', views.new_loan, name='new_loan'),
    # Page to handle loan return.
    path('return_loan/<int:loan_id>/', views.return_loan, name='return_loan'),
    # Page to handle loan return.
    path('returned_game/<int:game_id>/', views.returned_game, name='returned_game'),
    # Page to edit exsisting games
    path('edit_game/<int:game_id>/', views.edit_game, name='edit_game'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

boardgames/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here.

class Boardgame(models.Model):
    """Board games that are played"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    info = models.CharField(max_length=200)
    players = models.IntegerField()
    genre = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation on the model"""
        return self.name


# class Info (info about the game, genre, how many players... )
# one info per game?
# Can't these just be attributes of the class Boardgame instead? -Milla


# We don't need this anymore, right? -nina

#class Info(models.Model):
#    # info about the boardgame
#    boardgame = models.ForeignKey(Boardgame, on_delete=models.CASCADE)
#    text = models.TextField()
#    date_added = models.DateTimeField(auto_now_add=True)

# class Loans (who loaned and what and when)
# many loans per game

class Loan(models.Model):
    loaned_game = models.ForeignKey(Boardgame, on_delete=CASCADE)
    loaner = models.ForeignKey(User, on_delete=models.CASCADE)
    loaned = models.BooleanField(default=False)
    text = models.TextField()
    loan_started = models.DateTimeField(auto_now_add=True)
    loan_ended = models.DateTimeField(null=True)
    class Meta:
        verbose_name_plural = 'loans'

    def __str__(self):
         """Return a string representation on the model"""
         return f"{self.text[:50]}"
    
    def is_loaned(self):
        if self.loaned == True:
           if self.loan_ended == True:
            return self.loaner
        else:
            return self.loaned_game

    

users/models.py
from django.db import models

# Create your models here.

boardgames/forms.py
from django import forms


from .models import Boardgame, Loan

class BoardgameForm(forms.ModelForm):
    class Meta:
        model = Boardgame
        fields = ['name', 'info', 'players', 'genre']
        labels = {'name': 'Name', 'info': 'Info', 'players': 'Players', 'genre': 'Genre'}
        widgets = {'info': forms.Textarea(attrs={'cols': 80, 'rows': 5})}

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['loaned']
        labels = {'loaned': 'Want to loan this game?'}

class ReturnForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['loaned']
        labels = {'loaned': 'Want to loan this game?'}

boardgames/views.py
from django.http import request
from django.shortcuts import redirect, render
import datetime
from django.http import Http404
from django.contrib.auth.decorators import login_required

from .models import Boardgame, Loan
from .forms import BoardgameForm, LoanForm, ReturnForm

def index(request):
    """The homepage for Boardgames"""
    return render(request, 'boardgames/index.html')

@login_required
def games(request):
    """show all board games"""
    games = Boardgame.objects.order_by('date_added') #should it be ordered by alphabet??
    context = {'games' : games}
    return render(request, 'boardgames/games.html', context)

@login_required
def game(request, game_id):
    """Show a single game and its data"""
    game = Boardgame.objects.get(id=game_id)
    info = game.info #just one per game
    players = game.players
    owner = game.owner
    loans = game.loan_set.all()
    context = {'game' : game, 'info' : info, 'players' : players, 'owner' : owner, 'loans': loans}
    return render(request, 'boardgames/game.html', context)

@login_required
def new_game(request):
    """Add a new game"""
    if request.method != 'POST':
        #No data submitted; create blank form
        form = BoardgameForm()
    else:
        #POST data submitted, process data
        form = BoardgameForm(data=request.POST)
        if form.is_valid():
            new_game = form.save(commit=False)
            new_game.owner = request.user
            new_game.save()
            return redirect('boardgames:games')
        
    #Display a blank/invalid form
    context = {'form': form}
    return render(request, 'boardgames/new_game.html', context)

@login_required
def new_loan(request, game_id):
    """Loan a certain game"""
    game = Boardgame.objects.get(id=game_id)
    current_user = request.user

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = LoanForm
    else:
        # POST data submitted; process data.
        form = LoanForm(data=request.POST)
        if form.is_valid():
            gameloan = form.save(commit=False)
            gameloan.loaned_game = game
            gameloan.loaner = current_user
            gameloan.loaned = True
            gameloan.save()
            return redirect('boardgames:new_loan', game.id )
    
    # Display a blank or invalid form
    context = {'game': game, 'form': form}
    return render(request, 'boardgames/new_loan.html', context)

@login_required
def return_loan(request, loan_id):
    """Return a certain game"""
    loan = Loan.objects.get(id=loan_id)
    game = loan.loaned_game

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = ReturnForm
    else:
        # POST data submitted; process data.
        form = ReturnForm(instance=loan, data=request.POST)
        if form.is_valid():
            gamereturn = form.save(commit=False)
            gamereturn.loaned = False
            gamereturn.loan_ended = datetime.datetime.now()
            gamereturn.save()
            return redirect('boardgames:returned_game', game.id )
    
    # Display a blank or invalid form
    context = {'game': game, 'loan': loan, 'form': form}
    return render(request, 'boardgames/return_loan.html', context)

@login_required
def returned_game(request, game_id):
    """Game has been returned"""
    game = Boardgame.objects.get(id=game_id)   
    return render(request, 'boardgames/returned_game.html', {'game': game})

@login_required
def edit_game(request, game_id):
    """Edit an existing game"""
    game = Boardgame.objects.get(id=game_id)
    

    if request.method != 'POST':
        form = BoardgameForm(instance=game)
    else:
        # POST data submitted; process data.
        form = BoardgameForm(instance=game, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('boardgames:game', game_id=game.id)
    
    context = {'game' : game, 'form' : form }
    return render(request, 'boardgames/edit_game.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page
            login(request, new_user)
            return redirect('boardgames:index')

    # Display a blank form or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

boardgames/templates/boardgames/base.html
{% load bootstrap4 %}

 <!doctype html>
 <html lang="en">
 <head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
   <title>Board Games</title>

   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}
  </head> 


 <body>
   <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
       
     <a class="navbar-brand" href="{% url 'boardgames:index'%}">
         Board Games</a>

     <button class="navbar-toggler" type="button" data-toggle="collapse"
         data-target="#navbarCollapse" aria-controls="navbarCollapse"
         aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span></button>
     <div class="collapse navbar-collapse" id="navbarCollapse">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item">
           <a class="nav-link" href="{% url 'boardgames:games'%}">
               Games</a></li>
       </ul>
       <ul class="navbar-nav ml-auto">
         {% if user.is_authenticated %}
           <li class="nav-item">
             <span class="navbar-text"}">Hello, {{ user.username }}.</span>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
           </li>
         {% else %}
           <li class="nav-item">
             <a class="nav-link" href="{% url 'users:register' %}">Register</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
         {% endif %}
       </ul>
     </div>

   </nav>

   <main role="main" class="container">
     <div class="pb-2 mb-2 border-bottom">
       {% block page_header %}{% endblock page_header %}
     </div>
     <div>
       {% block content %}{% endblock content %}
     </div>
   </main>

 </body>

 </html>

boardgames/templates/boardgames/edit_game.html
{% extends "boardgames/base.html" %}



{% block content %}

    <h3><a href="{% url 'boardgames:game' game.id %}">{{ game }}</a> </h3>

    <form action="{% url 'boardgames:edit_game' game.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

boardgames/templates/boardgames/game.html
{% extends "boardgames/base.html" %}

{% block page_header %}
  <h3>{{ game }}</h3>
{% endblock page_header %}

{% block content %}


   <div class="card mb-3">
      <div class="card-body">
         <h6>Info</h6>
            <p>{{ info }}</p>
         <h6>Players</h6>
            <p>{{ players }}</p>
         <h6>Owner</h6>
            <p>{{ owner }}</p>
      </div>

   


   {% if user.is_authenticated %}

      {% for loan in loans %}

         {% if loan.loaned %}
            The game is loaned to  {{ loan.loaner }} starting {{ loan.loan_started }}
            
            {% if user == loan.loaner %}
               <form action="{% url 'boardgames:return_loan' loan.id %}" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-bg btn-primary" name='submit'>Return game</button>
               </form>
            {% endif %}
         {% endif %}
         
         {% if forloop.last %}
            {% if not loan.loaned %}
               The game is free! Loan it? 
   
               <form action="{% url 'boardgames:new_loan' game.id %}" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-bg btn-primary" name='submit'>Loan game</button>
               </form>  
            {% endif %}
         {% endif %}
      {% empty %}
      The game is free! Loan it? 
      
      <form action="{% url 'boardgames:new_loan' game.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-bg btn-primary" name='submit'>Loan game</button>
         </form>     
      {% endfor %}
   {% endif %}

   {% if user == game.owner %}
   <h5 class="card-header">
      <small><a href="{% url 'boardgames:edit_game' game.id %}">Edit game</a></small>
   </h5>
   </div>
   {% endif %}

{% endblock content %}

boardgames/templates/boardgames/games.html
{% extends "boardgames/base.html" %}

{% block page_header %}
  <h1>Games</h1>
{% endblock page_header %}

{% block content %}

   

   <ul>
       {% for game in games %}
         <li><h3>
           <a href="{% url 'boardgames:game' game.id %}">{{ game }}</a>
         </h3></li>
       {% empty %}
       <li><h3>No games have been added yet.</li>
       {% endfor %}
   </ul>

   <h3><a href="{% url 'boardgames:new_game' %}">Add a new game</a></h3>
{% endblock content %}

boardgames/templates/boardgames/index.html
{% extends "boardgames/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Play and borrow Board Games!</h1>
    
    <p class="lead">Keep track of your board games with Board Games! You can add a new board game whenever you want. </p>
 
    {% if not user.is_authenticated %}

    <a class="btn btn-bg btn-primary" href="{% url 'users:login' %}"
        role="button">Login &raquo;</a>
        <br><br>
        <h3>New here?</h3>
    <a class="btn btn-bg btn-primary" href="{% url 'users:register' %}"
           role="button">Register &raquo;</a>

    {% else %} 
        <a href="{% url 'boardgames:games' %}" >Gamelist</a>
    {% endif %}
  </div>
{% endblock page_header %}

boardgames/templates/boardgames/new_game.html
{% extends "boardgames/base.html" %}

{% block content %}

   <p>Add a new game:</p>

   <form action="{% url 'boardgames:new_game' %}" method='post'>
       {% csrf_token %}
       {{ form.as_p }}
       <button name="submit">Add game</button>
   </form>

{% endblock content %}

boardgames/templates/boardgames/new_loan.html
{% extends "boardgames/base.html" %}

{% block content %}
 <h3> Yay! You have now loaned <a href="{% url 'boardgames:game' game.id %}">{{ game }}</a></h3>

 <p>Enjoy playing and remember to return when you've played enough!</p>

 {% endblock content %}

boardgames/templates/boardgames/return_loan.html
{% extends "boardgames/base.html" %}

{% block content %}
    Intentionally blank
{% endblock content %}

boardgames/templates/boardgames/returned_game.html
{% extends "boardgames/base.html" %}

{% block content %}
 <h3>Yay! You have now returned <a href="{% url 'boardgames:game' game.id %}">{{ game }}</a>. </h3>

 {% endblock content %}